motd=§b§lBasqueCraft §7| §fServidor Anárquico 1.12.2
server-port=25565
online-mode=false
enable-command-block=true
spawn-protection=0
view-distance=10
max-players=150
pvp=true
allow-flight=true
difficulty=2
enable-rcon=false
generate-structures=true
level-type=DEFAULT